---
- hosts: all

  tasks:
    - name: flush iptables
      command: iptables -F
      
    - name: install epel-release
      yum: name=epel-release state=installed
    - name: install nginx
      yum: name=nginx state=present
    - name: start nginx
      service:
          name: nginx
          state: started
    
    - name: install redis
      yum: name=redis state=latest

    - name: redis start
      service: name=redis state=started enabled=yes

    - name: Add repository 'remi-repo'
      command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

    - name: install php70
      yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=installed
      with_items: 
        - php70
        - php70-php
        - php70-php-pdo
        - php70-php-bcmath
        - php70-php-pecl-imagick
        - php70-php-amqp

    - name: install phpmyadmin
      yum: name=phpmyadmin state=installed

    - name: install rpm mysql
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
      state: present

    - name: install mysqld
      yum: 
        name={{ item }}
        enablerepo=mysql56-community
        disablerepo=mysql57-community
        state=present
      with_items:
        - mysql-community-server
        - mysql-community-client
        - mysql-community-common
        - mysql-community-libs
        - mysql-community-libs-compat

    - name: mysqld start
      service:
        name=mysqld
        state=started
        enabled=yes
