---
- hosts: all

  tasks:

#    - name: Update package
#      command: yum update -y

    - name: Install pacckets
      yum:
        name: "{{ item }}"
      with_items:
        - wget
        - nano
        - git

    - name: Install epel-release
      yum: name=epel-release state=installed

    - name: Disable SELinux
      command: sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config


    - name: Open 80, 8080 ports
      firewalld:
        port: "{{item.port}}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - {port: '8080/tcp'}
        - {port: '80/tcp'}

    - name: Firewall reload
      command: firewall-cmd --reload

   
    - name: install nginx
      yum: name=nginx state=present

    - name: copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}" 
        mode: "{{ item.mode }}"
      with_items:
        - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf', mode: '0644' }
        - { src: 'index.php', dest: '/usr/share/nginx/html/index.php', mode: '0755' }
        - { src: 'phpmyadmin.sh', dest: '/tmp/phpmyadmin.sh', mode: '0755' }
        - { src: 'phpMyAdmin.conf', dest: '/etc/nginx/conf.d/phpMyAdmin.conf', mode: '0644' }

    - name: Install mysql from rep
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
      state: present


    - name: install mysqld
      yum:
        name={{ item }}
        enablerepo=mysql56-community
        disablerepo=mysql57-community
        state=present
      with_items:
        - mysql-community-server
        - mysql-community-client
        - mysql-community-common
        - mysql-community-libs
        - mysql-community-libs-compat

    - name: mysqld start
      service:
        name=mysqld
        state=started
        enabled=yes

    - name: Add ius repositary
      command: "{{ item  }}"
      with_items:
        - curl 'https://setup.ius.io/' -o setup-ius.sh
        - bash setup-ius.sh

#    - name: Add REMI for php7
#      command: rpm -Uvh "{{ item }}" 
#      with_items:
#        - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
#        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#        - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm        

    - name: Install php70u
      yum:
        name: "{{ item }}"
      with_items:
        - php70u
        - php70u-fpm
        - php70u-mysqlnd
        - php70u-mbstring
        - php70u-bcmath
        - php70u-pecl-imagick
        - php70u-pdo
        - php70u-pecl-amqp
        - php70u-json
        - php70u-cli 


    - name: Start php-fpm
      service: name=php-fpm state=started enabled=yes

    - name: Start nginx
      service: name=nginx state=started enabled=yes

    - name: Install redis
      yum: name=redis state=latest

    - name: Start redis 
      service: name=redis state=started enabled=yes

    - name: restart php-fpm
      service: name=php-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted


    - name: Install phpmyadmin
      command: bash "{{ item }}"
      with_items: 
        - /tmp/phpmyadmin.sh


#    - name: restart
#      command: reboot
